# Generated by Django 5.0.2 on 2024-02-16 15:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_section_product_additional_information_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_information',
            name='specification',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Information',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
