# Generated by Django 5.0.2 on 2024-02-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='app_Product',
        ),
    ]
