# Generated by Django 5.0.2 on 2024-02-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_product_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
