# Generated by Django 5.0.2 on 2024-02-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='product_slug',
        ),
    ]
