# Generated by Django 5.0.2 on 2024-02-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_slug_product_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_slug',
        ),
    ]
