# Generated by Django 5.0.2 on 2024-03-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
