# Generated by Django 5.0.2 on 2024-03-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
