# Generated by Django 5.0.2 on 2024-04-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
