# Generated by Django 5.0.2 on 2024-04-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
    ]
