# Generated by Django 5.0.2 on 2024-04-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
