# Generated by Django 5.0.2 on 2024-04-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
