# Generated by Django 5.0.2 on 2024-04-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_product_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_charge',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
    ]
