# Generated by Django 5.0.2 on 2024-04-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_product_delivery_charge_product_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
