# Generated by Django 5.0.2 on 2024-04-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
