# Generated by Django 5.0.2 on 2024-04-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_order_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon_Code',
        ),
    ]
