# Generated by Django 5.0.2 on 2024-04-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='when',
        ),
    ]
